export  { default as  Navbar } from './navbar/navbar'
export  {default as State } from './states/states'
export { default as CTA} from './cta/Cta'
export {default as Feature } from './feature/Feature'
export {default as Footer} from './footer/Footer'
